import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { Inter } from "next/font/google";
import BootstrapClient from ".//components/bootstrap/BootstrapClient.js";
import Navbar from "./components/navbar/Navbar.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "todo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body classNameName={inter.classNameName}>
        <Navbar />
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
